from __future__ import annotations

import hashlib
import json
from datetime import date, time
from decimal import Decimal
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from mbs.items import assign_manual_store_product_identifier, register_store_item
from mbs.models import AuditLog, Receipt, ReceiptItem, Store, StoreAliasKey, User
from mbs.receipts.persistence import _decimal_string


def create_manual_receipt(
    session: Session,
    actor: User,
    *,
    store_id: str,
    receipt_date: date,
    vendor_reference: str | None,
    receipt_time: time | None,
    subtotal: Decimal | None,
    tax: Decimal | None,
    total: Decimal,
    payment_method: str | None,
    lines: list[dict[str, Any]],
    source_event_id: str,
) -> Receipt:
    store = session.scalar(select(Store).where(Store.store_id == store_id).with_for_update())
    if store is None or not store.is_active or store.superseded_by_store_id is not None:
        raise ValueError("Select an active canonical store")
    if not lines:
        raise ValueError("At least one receipt line is required")
    normalized_reference = vendor_reference.strip() if vendor_reference else ""
    if len(normalized_reference) > 100:
        raise ValueError("Vendor reference must be 100 characters or fewer")
    if normalized_reference.upper().startswith("MANUAL:"):
        raise ValueError("MANUAL: receipt references are generated by the system")
    signature = _request_signature(
        {
            "actor_id": actor.id,
            "store_id": store_id,
            "receipt_date": receipt_date.isoformat(),
            "vendor_reference": normalized_reference,
            "receipt_time": receipt_time.isoformat() if receipt_time else None,
            "subtotal": _decimal_string(subtotal),
            "tax": _decimal_string(tax),
            "total": _decimal_string(total),
            "payment_method": payment_method,
            "lines": [
                {
                    key: value.value
                    if hasattr(value, "value")
                    else _decimal_string(value)
                    if isinstance(value, Decimal)
                    else value
                    for key, value in line.items()
                }
                for line in lines
            ],
        }
    )
    prior_receipt = session.scalar(
        select(Receipt).where(Receipt.source_event_id == source_event_id)
    )
    if prior_receipt is not None:
        if prior_receipt.source_request_signature != signature:
            raise ValueError("Manual receipt event ID was reused with another request")
        return prior_receipt
    alias_key = session.scalar(
        select(StoreAliasKey)
        .where(StoreAliasKey.store_id == store_id)
        .order_by(StoreAliasKey.normalized_key)
        .limit(1)
    )
    if alias_key is None:
        raise ValueError("Selected store has no source alias")
    transaction_number = normalized_reference or "MANUAL:PENDING"
    manual_time = receipt_time or time(0, 0)
    receipt = Receipt(
        receipt_id="MANUAL:PENDING",
        store_id=store.store_id,
        store_alias_key=alias_key.normalized_key,
        store=store.display_name,
        receipt_date=receipt_date,
        receipt_time=manual_time,
        transaction_number=transaction_number,
        source_type="MANUAL",
        source_event_id=source_event_id,
        source_request_signature=signature,
        subtotal=subtotal,
        tax=tax,
        total=total,
        payment_method=payment_method,
        raw_ocr_document={"source_type": "MANUAL"},
        receipt_document={},
    )
    session.add(receipt)
    session.flush()
    if not normalized_reference:
        transaction_number = f"MANUAL:{receipt.receipt_pk}"
        receipt.transaction_number = transaction_number
    receipt.receipt_id = _receipt_id(
        receipt.store, receipt.receipt_date, receipt.receipt_time, transaction_number
    )
    receipt_document: dict[str, object] = {
        "source_type": "MANUAL",
        "source_event_id": source_event_id,
        "receipt_pk": receipt.receipt_pk,
        "receipt_id": receipt.receipt_id,
        "store_id": receipt.store_id,
        "store": receipt.store,
        "date": receipt.receipt_date.isoformat(),
        "time": receipt.receipt_time.isoformat(),
        "vendor_reference": normalized_reference or None,
        "subtotal": _decimal_string(subtotal),
        "tax": _decimal_string(tax),
        "total": _decimal_string(total),
        "payment_method": payment_method,
        "items": [],
    }
    receipt_item_documents: list[dict[str, object]] = []
    receipt.receipt_document = receipt_document
    for source_line in lines:
        disposition = source_line["business_disposition"]
        subtype = source_line["disposition_subtype"]
        session.add(
            ReceiptItem(
                receipt_pk=receipt.receipt_pk,
                description=source_line["description"],
                upc=source_line.get("upc"),
                quantity=source_line.get("quantity"),
                unit_price=source_line.get("unit_price"),
                line_total=source_line["line_total"],
                category=source_line["category"],
                business_disposition=disposition.value,
                disposition_subtype=subtype.value,
                raw_ocr_item=None,
            )
        )
    session.flush()
    receipt_lines = session.scalars(
        select(ReceiptItem)
        .where(ReceiptItem.receipt_pk == receipt.receipt_pk)
        .order_by(ReceiptItem.id)
    ).all()
    for index, (receipt_line, line_input) in enumerate(zip(receipt_lines, lines, strict=True)):
        product_id = line_input.get("store_product_id")
        if product_id is None or not str(product_id).strip():
            store_item = assign_manual_store_product_identifier(session, receipt_line.id, actor.id)
        else:
            if str(product_id).strip().upper().startswith("MANUAL:"):
                raise ValueError("MANUAL: store product identifiers are generated by the system")
            store_item = register_store_item(
                session,
                store.store_id,
                str(product_id),
                receipt_line.description,
                receipt_line.upc,
                actor_id=actor.id,
                identifier_source="USER_ENTERED",
                effective_from=receipt.receipt_date,
            )
            receipt_line.store_item_id = store_item.store_item_id
            receipt_line.item_id = store_item.item_id
        receipt_item_documents.append(
            {
                "line_number": index + 1,
                "description": receipt_line.description,
                "store_product_id": store_item.store_product_id,
                "store_item_id": store_item.store_item_id,
                "item_id": receipt_line.item_id,
                "identifier_source": (
                    "MANUAL" if store_item.identifier_source == "MANUAL" else "USER_ENTERED"
                ),
                "upc": receipt_line.upc,
                "quantity": _decimal_string(receipt_line.quantity),
                "unit_price": _decimal_string(receipt_line.unit_price),
                "line_total": _decimal_string(receipt_line.line_total),
                "category": receipt_line.category,
                "business_disposition": receipt_line.business_disposition,
                "disposition_subtype": receipt_line.disposition_subtype,
            }
        )
    receipt.receipt_document = {
        **receipt_document,
        "items": receipt_item_documents,
    }
    session.add(
        AuditLog(
            event_type="MANUAL_RECEIPT_CREATED",
            actor=str(actor.id),
            entity_type="Receipt",
            entity_id=receipt.receipt_pk,
            details=json.dumps(
                {
                    "store_id": store.store_id,
                    "store_display_name": store.display_name,
                    "receipt_date": receipt_date.isoformat(),
                    "receipt_time": manual_time.isoformat(),
                    "vendor_reference": normalized_reference or None,
                    "generated_receipt_reference": (
                        transaction_number if not normalized_reference else None
                    ),
                    "subtotal": _decimal_string(subtotal),
                    "tax": _decimal_string(tax),
                    "total": _decimal_string(total),
                    "payment_method": payment_method,
                    "items": receipt_item_documents,
                },
                sort_keys=True,
            ),
        )
    )
    return receipt


def _receipt_id(store: str, receipt_date: date, receipt_time: time, reference: str) -> str:
    return f"{store}|{receipt_date.isoformat()}|{receipt_time.isoformat()}|{reference}"


def _request_signature(payload: dict[str, object]) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode()).hexdigest()
